<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>KumbiaPHP</title>
    <!-- Core CSS -->
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>css/app.css">
</head>
<body>
    <!-- Page Content -->
    <div class="container">
        <?php View::content() ?>        
    </div>
    <!-- /.container -->
<script src="<?= PUBLIC_PATH ?>javascript/jquery.min.js"></script>
<script src="<?= PUBLIC_PATH ?>javascript/bootstrap.min.js"></script>
</body>
</html>
