<!DOCTYPE html>
<html lang="en">
    <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>KumbiaPHP</title>

    <!-- Core CSS -->
    <link href="<?= PUBLIC_PATH; ?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= PUBLIC_PATH; ?>css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <script type="text/javascript" src="<?= PUBLIC_PATH; ?>javascript/jquery.min.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_PATH; ?>javascript/bootstrap.min.js"></script>
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>css/app.css">
</head>

<body>

    <!-- Page Content -->
    <div class="container">
        <?= View::content() ?>        
    </div>
    <!-- /.container -->

</body>

</html>

